LuaLS/LLS-Addons

- .gitmodules
- addons/nodemcu-esp32/info.json
Definition files for [NodeMCU](https://nodemcu.readthedocs.io/en/dev-esp32/), Lua based firmware for the ESP32 WiFi SoC from Espressif, to use with [Lua Language Server](https://github.com/LuaLS/lua-language-server).
> add: nodemcu esp32 definitions

- .gitmodules
- addons/nodemcu-esp8266/info.json
Definition files for [NodeMCU](https://nodemcu.readthedocs.io/en/dev/), a Lua based firmware for the ESP8266 WiFi SoC from Espressif, to use with [Lua Language Server](https://github.com/LuaLS/lua-language-server).
> add: nodemcu esp8266 definitions

- .gitmodules
- addons/argparse/info.json
Closes #9.
This includes all definitions from [goldenstein64/argparse-definitions/publish](https://github.com/goldenstein64/argparse-definitions/tree/publish). See the README on the [main branch](https://github.com/goldenstein64/argparse-definitions) for info on exactly what was added.
> Add argparse addon

- .gitmodules
- addons/penlight/info.json
Closes #8.
This includes all definitions from [goldenstein64/pl-definitions/publish](https://github.com/goldenstein64/pl-definitions/tree/publish). See the README on the [main branch](https://github.com/goldenstein64/pl-definitions) for info on exactly what was added. 
This has a plugin that detects `require("pl")`, `require("pl.compat")`, and comment counterparts for injecting Penlight modules into the global namespace. If a plugin is too much, I can instead publish two separate addons, one with global injections and another without.
> Add Penlight addon

- addons/argparse/info.json
- addons/bee/info.json
- addons/busted/info.json
- addons/cc-tweaked/info.json
- addons/cocos4.0/info.json
- addons/love-nuklear/info.json
- addons/love2d/info.json
- addons/lovr/info.json
- addons/lpeg/info.json
- addons/luaecs/info.json
- addons/luafilesystem/info.json
- addons/luaharfbuzz/info.json
- addons/luasocket/info.json
- addons/luassert/info.json
- addons/luazip/info.json
- addons/luvit/info.json
- addons/lzlib/info.json
- addons/md5/info.json
- addons/moonloader/info.json
- addons/openresty/info.json
- addons/penlight/info.json
- addons/skynet/info.json
- addons/slnunicode/info.json
- addons/tex-lualatex/info.json
- addons/tex-luatex/info.json
- addons/xmake/info.json
Instead of the URL to the old location
https://raw.githubusercontent.com/carsakiller/LLS-Addons/main/schemas/addon_info.schema.json
use the URL to the new location of the LLS-Addons repository.
https://raw.githubusercontent.com/LuaLS/LLS-Addons/main/schemas/addon_info.schema.json
Add additionally the missing $schema field to the info.json of the moonloader addon.
> Update all URLs to the schema file “addon_info.schema.json”

- .gitmodules
- addons/garrysmod/info.json
Closes #48
Adds addon with definitions for the game [Garry's Mod](https://gmod.facepunch.com/). The definitions are automatically generated and based on [the official wiki](https://wiki.facepunch.com/gmod)
The submodule points to the `lua-language-server-addon` branch in [this repo](https://github.com/luttje/glua-api-snippets/tree/lua-language-server-addon)
> Add garrysmod addon

- .gitmodules
- addons/yue/info.json
[Libyue](https://libyue.com) is a GUI library for C++, JS, and Lua. On the GitHub page, [there is a set of .json files which define the Yue API](https://github.com/yue/yue.github.io/tree/master/docs/latest/lua/api). The [`autogen.lua` file](https://github.com/Frityet/luayue-definitions/blob/generation/autogen.lua) automatically turns that into CATS definitions.
> Added yue (I don't know why github closes my PR when I pull updates)

- .gitmodules
- addons/transformice/info.json
adds support for transformice's [module api](https://transformice.fandom.com/wiki/Lua). the API runs with LuaJ 3.0 and not standard LuaC nor LuaJIT — it is basically an interpreter written against half-baked Lua 5.2 spec
the addon is suggested when `tfm.*` is typed.
> Addon for Transformice's Module API

- .gitmodules
- addons/lualogging/info.json
Closes #67.
This adds definitions for [lunarmodules/lualogging](https://github.com/lunarmodules/lualogging) from [goldenstein64/lualogging-definitions/publish](https://github.com/goldenstein64/lualogging-definitions/tree/publish). See the README on the [main branch](https://github.com/goldenstein64/lualogging-definitions) to see what was added.
This has a plugin that detects `require` calls to this library's appenders and injects them into fields on the `logging` table.
> Add LuaLogging addon

- .gitmodules
- addons/dkjson/info.json
This adds definitions for the [dkjson](http://dkolf.de/src/dkjson-lua.fsl) module from [goldenstein64/dkjson-definitions/publish](https://github.com/goldenstein64/dkjson-definitions/tree/publish). A README can be found on the [main branch](https://github.com/goldenstein64/dkjson-definitions/tree/main).
> Add dkjson addon

- .gitmodules
- addons/lua-cjson/info.json
This adds definitions for the [Lua CJSON](https://kyne.com.au/~mark/software/lua-cjson.php) module from [goldenstein64/lua-cjson-definitions/publish](https://github.com/goldenstein64/lua-cjson-definitions/tree/publish). A README can be found on the [main branch](https://github.com/goldenstein64/lua-cjson-definitions/tree/main).
> Add Lua CJSON addon

- .gitmodules
- addons/lapis/info.json
- addons/lua-cjson/info.json
The most widely used version of CJSON (to my knowledge) is OpenResty's fork of the module, found at [LuaRocks](https://luarocks.org/modules/openresty/lua-cjson) and at [openresty/lua-cjson](https://github.com/openresty/lua-cjson). My definitions only accounted for the original module, found [here](https://kyne.com.au/~mark/software/lua-cjson.php). This PR updates the CJSON definitions to reflect OpenResty's fork.
> Update Lua CJSON to use OpenResty's fork

- .gitmodules
- addons/StormworksAddonLua/info.json
Added support for Stormworks addon Lua. Contains definition for the server class, custom math class and others. Currently lacking server callbacks due to LuaLS not supporting them.
Related issue: #105
> Add stormworks addon lua

- addons/RavenscriptIDEA/info.json
fixed config.json on RSIDEA
OMG the config.json shouldn't have comments
when i tried to enable RSIDEA,the Addons maneger gave me a error. after i deleted config.json's comments,it works!
so i start a pr again, sorry
> fixed config.json on RSIDEA

- .gitmodules
- addons/starfallex/info.json
Adds the [Starfall-LLS](https://github.com/Periapsises/Starfall-LLS) addon, providing support for the [StarfallEx](https://github.com/thegrb93/StarfallEx) API within Lua LS.
Resolves #150
> Add Starfall Ex addon

- .gitmodules
- addons/smbx2-lunalua/info.json
Add definitions for [LunaLua](https://github.com/WohlSoft/LunaLua) (a fork of LuaJIT made for SMBX) and [SMBX2](https://codehaus.wohlsoft.ru) APIs.
Definitions are *accurate* but they are not *comprehensive* (it's probably around 80% or more complete, excluding modules). Updates are planned and hopefully some contributors from the smbx2 community will help finish this in the future.
> Add smbx2-lunalua addon

- .gitmodules
- addons/devilspie2/info.json
This addon is for writing scripts and config for https://github.com/dsalt/devilspie2
> Add devilspie2 addon

- .gitmodules
- addons/ncine/info.json
I would like to contribute the CATS definitions for the [nCine](https://ncine.github.io/), an open source cross-platform 2D game framework that can be used with both C++ and Lua.
The work took 2-3 weeks of my spare time and gave me the opportunity to review both the C++ Doxygen documentation and the Lua API itself. I would be really glad and proud if it gets accepted as an official addon for the Lua Language Server. 😊
Please don't hesitate to provide feedback and let me know if there is anything that should be changed. 🙏🏻 
GitHub Issue: #191.
> Add the nCine addon

- addons/ncine/info.json
I have updated the nCine submodule commit to point to the latest one where I have removed the trailing commas from `config.json` and `.luarc.json`.
Update: I have rebased this branch on top of the latest C.I. fixes (2).
> Update the nCine addons submodule

- .gitmodules
- addons/umbrella-unstable/info.json
Adds the Umbrella (Unstable) addon, which is type definitions for the Unstable (public beta) version of Project Zomboid's API. The justification for having two versions of the same addon is because these Unstable periods often last a long time (the previous one was two years) and each have significant playerbases and modding interest.
> Umbrella (Unstable) addon

- .gitmodules
- addons/luanti/info.json
https://blog.luanti.org/2024/10/13/Introducing-Our-New-Name/
> Update minetest module, rename to luanti

- addons/HLA-VScript/info.json
Fixes a syntax error causing the addon to fail enabling.
Comments present in the [example config.json on the wiki](https://luals.github.io/wiki/addons/#configjson) cause a syntax error when trying to enable the addon from the manager. I have removed all comments and it seems to enable correctly now.
The exact log was:
```
[2025-01-23 17:52:28] |  VERBOSE  |       Command      | Executing "enable" ({"command":"enable","data":{"name":"HLA-VScript"}})
[2025-01-23 17:52:29] |   DEBUG   |        Addon       | Initialized submodule
[2025-01-23 17:52:29] |   DEBUG   |        Addon       | Submodule up to date
[2025-01-23 17:52:29] |   ERROR   |        Addon       | Failed to read config.json file for HLA-VScript (SyntaxError: Expected property name or '}' in JSON at position 7 (line 2 column 5)) …
```
> Update HLA-VScript module

- .gitmodules
- addons/pico8/info.json
- addons/picotron/info.json
Stylua is quite confusing for me. I tried several times but still failed.
> Add PICO-8 and Picotron definitions #221

- .gitmodules
- addons/lsqlite3/info.json
Definition files for LuaSQLite3
https://lua.sqlite.org
> Add lsqlite3 addon

- addons/smbx2-lunalua/info.json
This update:
* Adds support for API changes from the new SMBX2 release Beta 5 Patch 3
* Removes known incorrect deprecation warnings (triggerEvent())
* Adds several missing LunaLua classes
* Generally improves annotations for many of the existing classes
* Renames some classes to better reflect their name as defined by LunaLua patches
> Update smbx2-lunalua module to smbxb5p3 apis

- .gitmodules
- addons/X4/info.json
In game by Egosoft - X4: Foundations the Lua used as an internal scripting language for the UI.
There is a data gathered by community and by analyse the Lua code from Egosoft.
There is an initial version. Description will be updated time to time.
Some functions will be moved from undocumented to the appropriate files.
> Add X4: Foundations Lua Scripts Functions and Type Definitions

- .gitmodules
- addons/darkrp/info.json
- addons/tex-luatex/info.json
in one of my last commits the definitions were changed to the starfall library and are incorrect, i've fixed the definitions and wiki references.
> Fixed definitions for darkrp module
