LuaLS/LLS-Addons

- .gitmodules
- addons/luvit/info.json
Seeing if the Github Action works on this one...
> add Luvit addon (x2)

- .gitmodules
Updates cc-tweaked and fixes its gitmodule url
> Update cc tweaked

- .gitmodules
- addons/xmake/info.json
> Add Xmake addon

- .gitmodules
- addons/luaunit/info.json
[LuaUnit ](https://github.com/bluebird75/luaunit)is a popular unit-testing framework for Lua, with an interface typical of xUnit libraries (Python unittest, Junit, NUnit, ...).
It supports several output formats (Text, TAP, JUnit, ...) to be used directly or work with Continuous Integration platforms (Jenkins, Hudson, ...).
> Add LuaUnit addon

- .gitmodules
- addons/minetest/info.json
The definitions are still incomplete but I think they can be useful to others.
There are some extra files, notably a 420KB file from which documentation is generated, not sure if that's too much
> Add Minetest addon

- .gitmodules
- addons/REFramework-LLS/info.json
Adds support for [REFramework](https://github.com/praydog/REFramework/), A mod framework, scripting platform, and modding tool for RE Engine games. 
Specifically, the addon provides basic autocomplete support for the lua scripting system (documented [here](https://cursey.github.io/reframework-book/index.html).)
> Addon for REFramework.

- CONTRIBUTING.md
- README.md
Changes links in README and CONTRIBUTING to refer to new wiki.
> Wiki migration

- .gitmodules
- addons/fivem/info.json
Add definitions for FiveM scripting API.
Closes #78
> feat(addons): FiveM

- .gitmodules
- addons/lldebugger/info.json
> Add lldebugger module

- .gitmodules
- addons/lapis/info.json
Adds definition files for [Lapis](https://leafo.net/lapis/).
> Add Lapis type definitions

- .gitmodules
- addons/ao/info.json
Adds definitions for all global variables as well as built in modules.
Related issue: [#111](https://github.com/LuaLS/LLS-Addons/issues/111)
> Add ao addon

- .gitmodules
- addons/RavenscriptIDEA/info.json
A community addon for ravenscript developing
the website is http://ravenfieldgame.com/ravenscript/
> add addon RSIDEA

- .gitmodules
- addons/StormworksAddonLua/info.json
Added old deprecated functions for maintaing older addons and more easily debugging them when the function was removed or deprecated.
Also fixed a mispelling in `server.dlcArid()`
Added:
- `server.getPlaylistCount()`
- `server.spawnMissionComponent()`
- `server.spawnVehicleSavefile()`
- `server.getPlaylistIndexByName()`
- `server.getPlaylistPath()`
- `server.setCharacterData()`
- `server.setOilSpill()` - I just forgot to add this one oops
- `server.getPlaylistIndexCurrent()`
- `server.getPlaylistData()`
- `server.dlcArid()` - typo from `server.dlcAriid()`
- `server.spawnMissionLocation()`
- `server.spawnThisAddonLocation()`
- `server.getStartIsland()`
- `server.spawnThisPlaylistMissionLocation()`
> Update stormworks addon lua

- .gitmodules
- addons/umbrella/info.json
Adds an addon for Umbrella, a definitions project for the game Project Zomboid.
> Add Umbrella addon

- .gitmodules
- addons/powder-toy/info.json
Adds addon from issue #128
I didn't run StyLua because it would remove spaces at the ends of lines in comments which would break the formatting in vscode.
I don't see an easy way to disable that in StyLua, please tell me if that can be fixed.
> Add Powder Toy addon

- .gitmodules
- addons/powder-toy/info.json
> Revert "Add Powder Toy addon"

- .gitmodules
- addons/powder-toy/info.json
New PR after #129 was reverted.
Fixes syntax error in info.json
> Re-Add Powder Toy addon

- .gitmodules
> Update Umbrella addon

- .gitmodules
- addons/fenster/info.json
Adds type definitions for my latest library, [lua-fenster](https://github.com/jonasgeiler/lua-fenster) (aka. [`fenster`](https://luarocks.org/modules/jonasgeiler/fenster) on luarocks.org).
Thanks in advance!
> Add lua-fenster

- .gitmodules
- addons/toml-edit/info.json
> Add toml-edit

- .gitmodules
Fixes incorrect path of `toml-edit`
> fix: toml-edit

- .gitmodules
This pull request introduces the following changes to smbx2-lunalua:
- More detailed and accurate annotations for the Graphics namespace
- Disable several additional standard library features
- Update several modules
- json
- xmem
- map3d
- orbits
- Add new modules
- npcmanager
- verletrope
- visioncone
- checkpoints
> Update smbx2-lunalua addon

- .gitmodules
- addons/trilogyloader/info.json
Definitions for the TrilogyLoader, a modding interface for GTA: SA - Definitive Edition
https://www.blast.hk/threads/220221/
> Add TrilogyLoader addon

- .gitmodules
- addons/scribunto/info.json
https://github.com/Dianliang233/scribunto-addon
> Add scribunto addon

- .gitmodules
- addons/ncine/info.json
> Revert "Add the nCine addon"

- .gitmodules
- addons/ncine/info.json
Adds ncine addon.
See original PR: https://github.com/LuaLS/LLS-Addons/pull/190
> add: ncine addon

- addons/ncine/info.json
Since the creation of the new [LDoc](https://ncine.github.io/docs/lua_master/) I have found various typos and cop/paste errors in the LuaLS definitions.
I fixed those while I have also renamed a couple of audio class tables, for clarity and coherence.
> Update the nCine addons submodule

- addons/ao/info.json
- Updates handlers module
- Updates ao library
- Adds incoming message actions
> Update `ao` submodule

- addons/trilogyloader/info.json
> TrilogyLoader addon update

- .gitmodules
- addons/HLA-VScript/info.json
This pull request adds definitions for the [Half Life Alyx API](https://developer.valvesoftware.com/wiki/Half-Life:_Alyx_Workshop_Tools/Scripting_API)
Many functions still have unknown uses or are broken in Half Life Alyx but are still present at runtime, so they are still defined by this addon even if not properly documented.
Closes #212
> Add HLA-VScript addon

- addons/umbrella-unstable/info.json
Updates the Umbrella (Unstable) addon to the latest version of the game.
> Update Umbrella (Unstable) addon

- addons/ncine/info.json
The latest changes to the nCine Lua API.
> Update definitions with new keyboard state methods

- .gitmodules
- addons/lua-enet/info.json
Adds type definitions for the lua bindings for lua-enet.
A common networking library that's also included natively in Löve.
> Add lua-enet type annotations

- addons/umbrella-unstable/info.json
Updates the Umbrella (Unstable) addon to the latest version of the game.
> Update Umbrella (Unstable)

- addons/starfallex/info.json
- Fix the string type not having access to the string library methods.
- Includes the latest updates from the Starfall Wiki.
> Update StarfallEx addon

- addons/garrysmod/info.json
Hi again,
Here's an update for the Garry's Mod library that:
- Fixes some formatting (newlines, unindenting, markdown table support) for annotations and other bugs (https://github.com/luttje/glua-api-snippets/pull/83)
- Adds `---@overload`'s for the `hook.Add` function (https://github.com/luttje/glua-api-snippets/pull/84)
- Includes updated documentation (scraped from the gmod wiki)
Thanks in advance for merging this.
Have a nice day!
> Updated garrysmod addon

- addons/ncine/info.json
- Update definitions with new joystick vibration functions
- Rename the function that returns the mapped joystick state
> Update nCine submodule

- .gitmodules
- addons/luaposix/info.json
> Add luaposix addon

- .gitmodules
- addons/darkrp/info.json
- addons/tex-luatex/info.json
Added definitions for for darkrp gamemode in garry's mod.
> added DarkRP module
